[build]
  publish = "public"
  functions = "functions"

[functions]
  external_node_modules = ["serverless-http", "@sparticuz/chromium"]

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/api/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
